## Descriptor Calculation and EDA

### Installing conda and rdkit
- I am using rdkit to compute the molecular descriptors for the compounds in the previously collected dataset
- Th dataset is comprised of the molecule names and the corresponding SMILES notation (information about the chemical structure) 
- I will use the SMILES notation to compute the molecular descriptors.
- The dataset also contains the IC50 - have already performed the binning into the bioactivity class (active, inactive, intermediate)
- I will select two activity classes (active and inactive) to easily compare between the active and inactive compounds

In [3]:
from rdkit import Chem
from rdkit.Chem import Draw

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

### Load bioactivity data

In [5]:
import pandas as pd

In [7]:
df = pd.read_csv('bioactivity_preprocessed_data.csv')

## Calculate Lipinski descriptors
- rule-of-thumb for evaluating the __druglikeness__ of compounds baed on __Absorption__, __Distribution__, __Metabolism__, __Excretion (ADME)__ that is also known as pharmacokineic profile
- Lipinski analyzed all orally active FDA-approced drugs in the formulation of the __Rule-of-Five (Lipinski's Rule)__

The Lipinski's Rule staed the following:
- Molecular weight < 500 Dalton
- Octanol-water partition coefficient (LogP) < 5
- Hydrogen bond donors < 5
- Hydrogen bon acceptors < 10

#### Import libraries

In [8]:
import numpy as np
from rdkit import Chem
from rdkit.Chem import Descriptors, Lipinski

### Calculate descriptors

In [9]:
# Inspired by: https://codeocean.com/explore/capsules?query=tag:data-curation

def lipinski(smiles, verbose=False):

    moldata= []
    for elem in smiles:
        mol=Chem.MolFromSmiles(elem) 
        moldata.append(mol)
       
    baseData= np.arange(1,1)
    i=0  
    for mol in moldata:        
       
        desc_MolWt = Descriptors.MolWt(mol)
        desc_MolLogP = Descriptors.MolLogP(mol)
        desc_NumHDonors = Lipinski.NumHDonors(mol)
        desc_NumHAcceptors = Lipinski.NumHAcceptors(mol)
           
        row = np.array([desc_MolWt,
                        desc_MolLogP,
                        desc_NumHDonors,
                        desc_NumHAcceptors])   
    
        if(i==0):
            baseData=row
        else:
            baseData=np.vstack([baseData, row])
        i=i+1      
    
    columnNames=["MW","LogP","NumHDonors","NumHAcceptors"]   
    descriptors = pd.DataFrame(data=baseData,columns=columnNames)
    
    return descriptors

In [10]:
df_lipinski = lipinski(df.canonical_smiles)

### Combine DataFrames

In [11]:
df_lipinski

          MW     LogP  NumHDonors  NumHAcceptors
0    281.271  1.89262         0.0            5.0
1    415.589  3.81320         0.0            2.0
2    421.190  2.66050         0.0            4.0
3    293.347  3.63080         0.0            3.0
4    338.344  3.53900         0.0            5.0
..       ...      ...         ...            ...
240  328.466  3.34562         1.0            5.0
241  222.379 -1.99300         1.0            3.0
242  485.559  0.54470         5.0            7.0
243  222.379 -1.99300         1.0            3.0
244  485.559  0.54470         5.0            7.0

[245 rows x 4 columns]

In [12]:
df

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL187579,Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C#N)ccc21,7200.00
1,CHEMBL188487,O=C1C(=O)N(Cc2ccc(F)cc2Cl)c2ccc(I)cc21,9400.00
2,CHEMBL185698,O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21,13500.00
3,CHEMBL426082,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21,13110.00
4,CHEMBL187717,O=C1C(=O)N(Cc2cc3ccccc3s2)c2c1cccc2[N+](=O)[O-],2000.00
...,...,...,...
240,CHEMBL4590273,Cc1cccc2nc(CSC(=S)NCc3cccnc3)cn12,380.19
241,CHEMBL5436771,S=C([S-])NCc1cccnc1.[K+],165.00
242,CHEMBL2365410,CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](CC1C...,161.00
243,CHEMBL5436771,S=C([S-])NCc1cccnc1.[K+],165.96
244,CHEMBL2365410,CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](CC1C...,162.18

Combining the df dataframe and Lipinski dataframe together to have the standard value and bioactivity class columns

In [13]:
df_combined = pd.concat([df, df_lipinski], axis = 1)

In [14]:
df_combined

,molecule_chembl_id,canonical_smiles,standard_value,MW,LogP,NumHDonors,NumHAcceptors
0,CHEMBL187579,Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C#N)ccc21,7200.00,281.271,1.89262,0.0,5.0
1,CHEMBL188487,O=C1C(=O)N(Cc2ccc(F)cc2Cl)c2ccc(I)cc21,9400.00,415.589,3.81320,0.0,2.0
2,CHEMBL185698,O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21,13500.00,421.190,2.66050,0.0,4.0
3,CHEMBL426082,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21,13110.00,293.347,3.63080,0.0,3.0
4,CHEMBL187717,O=C1C(=O)N(Cc2cc3ccccc3s2)c2c1cccc2[N+](=O)[O-],2000.00,338.344,3.53900,0.0,5.0
...,...,...,...,...,...,...,...
240,CHEMBL4590273,Cc1cccc2nc(CSC(=S)NCc3cccnc3)cn12,380.19,328.466,3.34562,1.0,5.0
241,CHEMBL5436771,S=C([S-])NCc1cccnc1.[K+],165.00,222.379,-1.99300,1.0,3.0
242,CHEMBL2365410,CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](CC1C...,161.00,485.559,0.54470,5.0,7.0
243,CHEMBL5436771,S=C([S-])NCc1cccnc1.[K+],165.96,222.379,-1.99300,1.0,3.0
244,CHEMBL2365410,CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](CC1C...,162.18,485.559,0.54470,5.0,7.0

### Convert IC50 to pIC50

The original IC50 values have uneven distribution of data points. To allow __IC50__ data to be more uniformly distributed, 
I am converting __IC50__ to the negative logarithmic scale, which is essentially __-log10(IC50)__


This custom function pIC50() will accept a DataFrame as input and will:
- Take the IC50 values from standard_value column and converts it from nM to M by multiplying the value by 10^-9
- Take the molar value and apply -log10
- Delete the standard_value column and create a new pIC50 column

In [55]:

# https://github.com/chaninlab/estrogen-receptor-alpha-qsar/blob/master/02_ER_alpha_RO5.ipynb

import numpy as np

def pIC50(input_df):
    df = input_df.copy()

    pIC50_values = []
    for val in df['standard_value_norm']:
        molar = val * 1e-9
        pIC50_values.append(-np.log10(molar))

    df['pIC50'] = pIC50_values
    df = df.drop('standard_value_norm', axis=1)

    return df

In [56]:
df_combined.standard_value.describe()

count    2.450000e+02
mean     6.893878e+04
std      1.851962e+05
min      5.000000e+01
25%      5.000000e+03
50%      1.500000e+04
75%      4.700000e+04
max      2.000000e+06
Name: standard_value, dtype: float64

Point to note: Values greater than 100,000,000 will be fixed at 100,000,000 otherwise the negative logarithmic value will become negative. To prevent this, I am going to cap the maximum value to be 100,000

In [57]:
-np.log10((10**-9)*100000000)

np.float64(1.0)

In [58]:
-np.log10((10**-9)* 10000000000)

np.float64(-1.0)

In [59]:
def norm_value(input_df):
    df = input_df.copy()

    norm = []
    for val in df['standard_value']:
        if val > 100000:
            norm.append(100000)
        else:
            norm.append(val)

    df['standard_value_norm'] = norm
    df = df.drop('standard_value', axis=1)

    return df

norm_value will read through the values in the standard_value column and cap the values at 100000000, so that the standard_value column is normalized.

In [60]:

df_norm = norm_value(df_combined)
df_norm

,molecule_chembl_id,canonical_smiles,MW,LogP,NumHDonors,NumHAcceptors,standard_value.norm,standard_value_norm
0,CHEMBL187579,Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C#N)ccc21,281.271,1.89262,0.0,5.0,7200.00,7200.00
1,CHEMBL188487,O=C1C(=O)N(Cc2ccc(F)cc2Cl)c2ccc(I)cc21,415.589,3.81320,0.0,2.0,9400.00,9400.00
2,CHEMBL185698,O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21,421.190,2.66050,0.0,4.0,13500.00,13500.00
3,CHEMBL426082,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21,293.347,3.63080,0.0,3.0,13110.00,13110.00
4,CHEMBL187717,O=C1C(=O)N(Cc2cc3ccccc3s2)c2c1cccc2[N+](=O)[O-],338.344,3.53900,0.0,5.0,2000.00,2000.00
...,...,...,...,...,...,...,...,...
240,CHEMBL4590273,Cc1cccc2nc(CSC(=S)NCc3cccnc3)cn12,328.466,3.34562,1.0,5.0,380.19,380.19
241,CHEMBL5436771,S=C([S-])NCc1cccnc1.[K+],222.379,-1.99300,1.0,3.0,165.00,165.00
242,CHEMBL2365410,CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](CC1C...,485.559,0.54470,5.0,7.0,161.00,161.00
243,CHEMBL5436771,S=C([S-])NCc1cccnc1.[K+],222.379,-1.99300,1.0,3.0,165.96,165.96
244,CHEMBL2365410,CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](CC1C...,485.559,0.54470,5.0,7.0,162.18,162.18

In [61]:
df_norm.standard_value_norm.describe()

count       245.000000
mean      30301.541347
std       33786.093480
min          50.000000
25%        5000.000000
50%       15000.000000
75%       47000.000000
max      100000.000000
Name: standard_value_norm, dtype: float64

In [62]:
df_final = pIC50(df_norm)
df_final

,molecule_chembl_id,canonical_smiles,MW,LogP,NumHDonors,NumHAcceptors,standard_value.norm,pIC50
0,CHEMBL187579,Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C#N)ccc21,281.271,1.89262,0.0,5.0,7200.00,5.142668
1,CHEMBL188487,O=C1C(=O)N(Cc2ccc(F)cc2Cl)c2ccc(I)cc21,415.589,3.81320,0.0,2.0,9400.00,5.026872
2,CHEMBL185698,O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21,421.190,2.66050,0.0,4.0,13500.00,4.869666
3,CHEMBL426082,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21,293.347,3.63080,0.0,3.0,13110.00,4.882397
4,CHEMBL187717,O=C1C(=O)N(Cc2cc3ccccc3s2)c2c1cccc2[N+](=O)[O-],338.344,3.53900,0.0,5.0,2000.00,5.698970
...,...,...,...,...,...,...,...,...
240,CHEMBL4590273,Cc1cccc2nc(CSC(=S)NCc3cccnc3)cn12,328.466,3.34562,1.0,5.0,380.19,6.419999
241,CHEMBL5436771,S=C([S-])NCc1cccnc1.[K+],222.379,-1.99300,1.0,3.0,165.00,6.782516
242,CHEMBL2365410,CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](CC1C...,485.559,0.54470,5.0,7.0,161.00,6.793174
243,CHEMBL5436771,S=C([S-])NCc1cccnc1.[K+],222.379,-1.99300,1.0,3.0,165.96,6.779997
244,CHEMBL2365410,CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](CC1C...,485.559,0.54470,5.0,7.0,162.18,6.790003

In [64]:
df_final.pIC50.describe()

count    245.000000
mean       4.959231
std        0.817871
min        4.000000
25%        4.327902
50%        4.823909
75%        5.301030
max        7.301030
Name: pIC50, dtype: float64

### Removing the 'intermediate' bioactivity class